apiVersion: kafka.strimzi.io/v1
kind: KafkaConnector
metadata:
  name: timer-connector
  namespace: kafka
  labels:
    strimzi.io/cluster: my-connect-cluster
spec:
  class: org.apache.camel.kafkaconnector.timersource.CamelTimersourceSourceConnector
  tasksMax: 1
  config:
    topics: timer-topic
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: org.apache.kafka.connect.storage.StringConverter
    camel.kamelet.timer-source.message: "hello from kafka connect"
    camel.kamelet.timer-source.period: 3000
